project:
  type: website

website:
  title: "quarto2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Test.qmd
      - Tuto1.qmd
      - Graph.qmd
    right:
      - icon: github
        href: https://github.com/marcgarel/quarto2.github.io

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



